/**
 * Small first-load manifest used by the muscle list. The full guide payload is
 * loaded only when the needle dialog opens. A test keeps this set in sync with
 * the chapter 13 guide definitions.
 */
const imageGuideCatalogNames = new Set([
  'Abd. Digiti Minimi',
  'Abd. Pollicis Brevis',
  'Abductor Digiti Quinti',
  'Abductor Hallucis',
  'Adductor Longus/Brevis',
  'Adductor Magnus',
  'Anconeus',
  'Biceps Brachii',
  'Biceps Femoris (Long Head)',
  'Biceps Femoris (Short Head)',
  'Brachioradialis',
  'Deltoid (Ant/Mid/Post)',
  'Extensor Carpi Rad. Longus',
  'Extensor Carpi Ulnaris',
  'Extensor Digitorum Brevis',
  'Extensor Digitorum Communis',
  'Extensor Digitorum Longus',
  'Extensor Hallucis Longus',
  'Extensor Indicis Proprius',
  'First Dorsal Interosseous',
  'Flexor Carpi Radialis',
  'Flexor Carpi Ulnaris',
  'Flexor Digitorum Longus',
  'Flexor Digitorum Profundus (1,2)',
  'Flexor Digitorum Profundus (3,4)',
  'Flexor Digitorum Superficialis',
  'Flexor Hallucis Brevis',
  'Flexor Pollicis Brevis',
  'Flexor Pollicis Longus',
  'Frontalis',
  'Gastrocnemius (Med/Lat)',
  'Gluteus Major',
  'Gluteus Medius',
  'Gracilis',
  'Iliopsoas',
  'Infraspinatus',
  'Latissimus Dorsi',
  'Masseter',
  'Mentalis',
  'Opponens Pollicis',
  'Orbicularis Oculi',
  'Paraspinal (Cervical)',
  'Paraspinal (L2)',
  'Paraspinal (L3)',
  'Paraspinal (L4)',
  'Paraspinal (L5)',
  'Paraspinal (S1)',
  'Paraspinal (Thoracic)',
  'Pectoralis Major (Clav)',
  'Pectoralis Major (Stern)',
  'Peroneus Longus',
  'Pronator Quadratus',
  'Pronator Teres',
  'Quadriceps (Vastus/Rectus)',
  'Rhomboid Major/Minor',
  'Semimembranosus',
  'Semitendinosus',
  'Serratus Anterior',
  'Soleus',
  'Sternocleidomastoid',
  'Supraspinatus',
  'Tensor Fasciae Latae',
  'Teres Minor',
  'Tibialis Anterior',
  'Tibialis Posterior',
  'Tongue (Genioglossus)',
  'Trapezius (Upper)',
  'Triceps Brachii',
])

export function hasNeedleGuideImage(muscleName: string): boolean {
  return imageGuideCatalogNames.has(muscleName)
}

export const needleGuideImageCatalogNames = [...imageGuideCatalogNames]
