export interface SupplementalNeedleGuideInput {
  id: string
  chineseName: string
  englishName: string
  catalogNames: string[]
  innervation: string
  insertion: string
  activation: string
  clinicalPoints: string[]
  anatomyPoints: string[]
}

/**
 * Text-only supplements for catalog muscles that do not have a Chapter 13
 * figure. These deliberately avoid fixed needle depths: surface landmarks,
 * palpation and selective activation must be adapted to the individual.
 */
export const supplementalNeedleGuideInputs: SupplementalNeedleGuideInput[] = [
  {
    id: 'supplement-orbicularis-oris', chineseName: '口輪匝肌', englishName: 'Orbicularis Oris', catalogNames: ['Orbicularis Oris'],
    innervation: '顏面神經（CN VII）；主要為頰支與下頷緣支。',
    insertion: '沿口唇周圍肌肉走向採表淺切線進針；先請病人噘嘴以觸診並確認肌肉邊界。',
    activation: '請病人噘嘴或緊閉雙唇。',
    clinicalPoints: ['可用於 facial nerve disorder 的 nEMG 評估，需依病程與完整 facial EDX 組合判讀。', '小型 facial muscles 的 motor unit 組成與肢體肌不同，MUAP 判讀前須先確認針尖確在目標肌。'],
    anatomyPoints: ['避免深刺進入口腔黏膜。', '外側接近顏面動脈分支；有明顯血管搏動或局部感染時改換位置。'],
  },
  {
    id: 'supplement-nasalis', chineseName: '鼻肌', englishName: 'Nasalis', catalogNames: ['Nasalis'],
    innervation: '顏面神經（CN VII）頰支。',
    insertion: '在鼻翼外側或鼻背下半部，以極表淺切線方式進入可觸及的肌層。',
    activation: '請病人皺鼻或擴張鼻孔。',
    clinicalPoints: ['提供顏面神經中段分支與顱延髓肌取樣。', '需以選擇性動作確認，避免記錄到鄰近提上唇肌。'],
    anatomyPoints: ['肌肉很薄，避免深入鼻軟骨與鼻腔。', '避開可見的鼻部血管與皮膚發炎區。'],
  },
  {
    id: 'supplement-temporalis', chineseName: '顳肌', englishName: 'Temporalis', catalogNames: ['Temporalis'],
    innervation: '三叉神經下頷支（CN V3）的深顳神經。',
    insertion: '在顴弓上方的顳窩，先請病人咬緊牙關觸診肌腹，再於觸診範圍內進針。',
    activation: '請病人咬緊牙關。',
    clinicalPoints: ['可與咬肌共同評估三叉神經運動支、腦幹或顱延髓病變。', '顱面肌 MUAP 與肢體肌不同，應與熟悉的顳肌正常型態比較。'],
    anatomyPoints: ['避開耳前可觸及的淺顳動脈。', '顳骨位於深層，避免不必要的深刺與反覆探針。'],
  },
  {
    id: 'supplement-levator-scapulae', chineseName: '提肩胛肌', englishName: 'Levator Scapulae', catalogNames: ['Levator Scapulae'],
    innervation: '肩胛背神經與 C3-C4 頸神經分支，主要 C3-C5。',
    insertion: '沿肩胛骨內上角至上頸椎方向觸診肌腹；以肩胛骨內上角為骨性基準，在可確定肌腹處進針。',
    activation: '請病人抗阻聳肩；以觸診到提肩胛肌的選擇性收縮為準。',
    clinicalPoints: ['可協助評估 C3-C5 神經根、肩胛背神經與近端肩帶病變。', '應與斜方肌、菱形肌及頸椎脊旁肌分開確認。'],
    anatomyPoints: ['下段靠近胸廓，進針方向不可朝向肋間隙。', '深部可鄰近肩胛背神經與血管；解剖界線不清時採超音波導引。'],
  },
  {
    id: 'supplement-subclavius', chineseName: '鎖骨下肌', englishName: 'Subclavius', catalogNames: ['Subclavius'],
    innervation: '鎖骨下肌神經、上幹，C5-C6。',
    insertion: '本工具目前沒有找到可驗證的一般 diagnostic needle EMG 路徑，因此不提供固定位置、角度或深度。',
    activation: '請病人向下、向前穩定肩帶。',
    clinicalPoints: ['目前只核對到 anatomy 與區域性 safety 資料，不能把本頁當作可直接執行的進針 protocol。', 'AANEM 建議依病人的個別風險與檢查效益決定是否進行高風險部位的 needle EMG。'],
    anatomyPoints: ['supraclavicular／胸壁區鄰近胸膜與肺；ultrasound 可增加定位準確度，但 AANEM 未宣稱已證明可消除風險。', '鎖骨下血管、臂神經叢與肺尖均位於鄰近區域。'],
  },
  {
    id: 'supplement-pectoralis-minor', chineseName: '胸小肌', englishName: 'Pectoralis Minor', catalogNames: ['Pectoralis Minor'],
    innervation: '內側胸神經為主，內側索，C8-T1（可有 C6-C7 變異）。',
    insertion: '胸小肌位於胸大肌深層、由肋骨走向喙突；先以肩胛前引確認，若無法明確分辨層次，不宜盲刺。',
    activation: '請病人前引並下壓肩胛骨。',
    clinicalPoints: ['本頁僅把胸小肌列為內側胸神經／C8-T1 的補充取樣參考，不能單靠此肌定位病灶。', '需以深度、位置與選擇性 activation 確認不是記錄到胸大肌。'],
    anatomyPoints: ['胸壁肌進針可能造成氣胸；應先進行個別 benefit-risk 評估。', 'Ultrasound 可協助確認目標與深度，但 AANEM 指引未認定它已被證明可消除併發症風險。'],
  },
  {
    id: 'supplement-subscapularis', chineseName: '肩胛下肌', englishName: 'Subscapularis', catalogNames: ['Subscapularis'],
    innervation: '上、下肩胛下神經，後索，C5-C7。',
    insertion: '本工具目前沒有找到可驗證的一般 diagnostic needle EMG 路徑，因此不提供固定位置、角度或深度。',
    activation: '請病人內旋肩關節。',
    clinicalPoints: ['目前只有 anatomy／ultrasound 橫切面資料，不能把本頁當作已驗證的 diagnostic needle route。', '在嚴重無力或解剖改變時，單靠 activation 不足以證實針位。'],
    anatomyPoints: ['橫切面可見鄰近腋動靜脈、臂神經叢與胸壁；不能由該影像推導固定盲刺角度或深度。', 'Saddler 等人把 ultrasound 定位定位為困難目標的輔助工具，仍須依操作者訓練與個別 anatomy 判斷。'],
  },
  {
    id: 'supplement-teres-major', chineseName: '大圓肌', englishName: 'Teres Major', catalogNames: ['Teres Major'],
    innervation: '下肩胛下神經，後索，C5-C7。',
    insertion: '在肩胛骨下角外側、後腋襞上方觸診肌腹；以抗阻內旋及內收確認邊界後進針。',
    activation: '請病人內旋並內收肩關節。',
    clinicalPoints: ['可與背闊肌、肩胛下肌比較後索的近端分支。', '需與位於上方的小圓肌及下方的背闊肌區分。'],
    anatomyPoints: ['前深方鄰近腋窩神經血管構造。', '無法清楚觸診後腋襞與肌腹時採超音波確認。'],
  },
  {
    id: 'supplement-brachialis', chineseName: '肱肌', englishName: 'Brachialis', catalogNames: ['Brachialis'],
    innervation: '肌皮神經，外側索、上幹，C5-C6；外側部分可接受橈神經分支。',
    insertion: '在上臂遠端三分之一將肱二頭肌推向內側，於肱二頭肌與肱三頭肌之間的溝內進針。',
    activation: '請病人輕度屈肘；前臂旋前或旋後本身不能證實針尖位於肱肌。',
    clinicalPoints: ['可評估肌皮神經、上幹或 C5-C6 神經根病變。', 'Menkes & Pierce 指出 forearm pronation／supination 對肱肌 activation 並無關鍵影響；應以 anatomy-first 定位。'],
    anatomyPoints: ['保持在可觸及的肱肌邊界內，避免向內側深刺至肱動脈與正中神經。', '外側進針需注意橈神經路徑。'],
  },
  {
    id: 'supplement-coracobrachialis', chineseName: '喙肱肌', englishName: 'Coracobrachialis', catalogNames: ['Coracobrachialis'],
    innervation: '肌皮神經，外側索、上幹，C5-C7。',
    insertion: '在上臂近端內側，沿喙突至肱骨內側中段方向，先以抗阻肩屈曲及內收觸診狹長肌腹。',
    activation: '請病人屈曲並內收肩關節。',
    clinicalPoints: ['提供肌皮神經較近端的取樣。', '肌腹較小且深，activation 不能取代解剖定位。'],
    anatomyPoints: ['肌皮神經穿越肌肉；內側鄰近肱動脈、正中神經與尺神經。', '解剖界線不清或肌肉萎縮時建議超音波導引。'],
  },
  {
    id: 'supplement-ecrb', chineseName: '橈側伸腕短肌', englishName: 'Extensor Carpi Radialis Brevis (ECRB)', catalogNames: ['Extensor Carpi Rad. Brevis'],
    innervation: '橈神經的 ECRB 分支，後索；常列 C6-C7，但不同參考資料對 root 範圍並不完全一致。',
    insertion: '在外上髁遠端的近端背外側前臂，觸診抗阻伸腕肌群；選擇 ECRL 內側、指伸肌外側的肌腹。',
    activation: '請病人伸腕並稍向橈側偏移。',
    clinicalPoints: ['可協助定位橈神經深支或後骨間神經近端病變。', '應與 ECRL、EDC 以位置與選擇性動作區分。'],
    anatomyPoints: ['橈神經深支位於鄰近深層；避免不必要的深刺。', '若需精確區分 ECRB 與鄰肌，可用超音波確認。'],
  },
  {
    id: 'supplement-supinator', chineseName: '旋後肌', englishName: 'Supinator', catalogNames: ['Supinator'],
    innervation: '橈神經深支／後骨間神經，後索，C6-C7。',
    insertion: '位於近端橈骨外側的深層；在肱橈肌及伸腕肌群深面，僅靠表面 landmark 不易可靠命中。',
    activation: '肘伸直時請病人旋後前臂。',
    clinicalPoints: ['可協助區分 C5-C6 radiculopathy 與橈神經病變。', '屬深層且多肌共同參與旋後，建議以影像確認針位。'],
    anatomyPoints: ['後骨間神經穿過旋後肌，避免盲目深刺與反覆探針。', '建議超音波導引。'],
  },
  {
    id: 'supplement-apl', chineseName: '拇長展肌', englishName: 'Abductor Pollicis Longus (APL)', catalogNames: ['Abd. Pollicis Longus'],
    innervation: '後骨間神經，後索，C7-C8。',
    insertion: '在前臂遠端背外側、伸肌支持帶近端觸診肌腹；以拇指掌腕關節外展確認。',
    activation: '請病人在掌腕關節外展拇指。',
    clinicalPoints: ['可評估後骨間神經、橈神經或 C7-C8 病變。', '須與 EPB 及橈側伸腕肌的共同動作區分。'],
    anatomyPoints: ['遠端鄰近淺橈神經與橈動脈分支。', '針點應位於肌腹而不是第一伸肌腱室。'],
  },
  {
    id: 'supplement-epl', chineseName: '拇長伸肌', englishName: 'Extensor Pollicis Longus (EPL)', catalogNames: ['Ext. Pollicis Longus'],
    innervation: '後骨間神經，後索，C7-C8。',
    insertion: '在前臂遠端背側、伸肌支持帶近端尋找肌腹；以拇指指間關節伸展確認。',
    activation: '請病人伸展拇指指間關節。',
    clinicalPoints: ['可評估後骨間神經與 C7-C8 病變。', 'EPL 肌腹細長，應避免把鄰近 EDC 或 EPB 當成目標。'],
    anatomyPoints: ['針點須在肌腹、不要刺入 Lister 結節周圍的肌腱區。', '解剖不清時以超音波定位。'],
  },
  {
    id: 'supplement-epb', chineseName: '拇短伸肌', englishName: 'Extensor Pollicis Brevis (EPB)', catalogNames: ['Ext. Pollicis Brevis'],
    innervation: '後骨間神經，後索，C7-C8。',
    insertion: '在前臂遠端背外側、伸肌支持帶近端觸診較短肌腹；以拇指掌指關節伸展確認。',
    activation: '請病人伸展拇指掌指關節。',
    clinicalPoints: ['與 EIP、ECU 合併取樣可協助比較下幹和內側索病變。', '須與 APL 及 EPL 以關節動作區分。'],
    anatomyPoints: ['遠端鄰近淺橈神經。', '針點應位於肌腹而非第一伸肌腱室。'],
  },
  {
    id: 'supplement-palmaris-longus', chineseName: '掌長肌', englishName: 'Palmaris Longus', catalogNames: ['Palmaris Longus'],
    innervation: '正中神經，外側索與內側索，C7-C8。',
    insertion: '令拇指與小指相對並輕度屈腕；若可見掌長肌腱，在前臂中段沿肌腱近端觸診肌腹後進針。',
    activation: '請病人輕度屈腕並繃緊掌腱膜。',
    clinicalPoints: ['可作為正中神經支配的 C7-C8 比較肌。', '此肌可能先天缺如；找不到肌腱時不要反覆盲刺。'],
    anatomyPoints: ['確認不是橈側伸腕肌或尺側伸腕肌。', '向深層或內側偏移時需注意正中神經與尺側神經血管構造。'],
  },
  {
    id: 'supplement-lumbricals-hand', chineseName: '第一、二蚓狀肌', englishName: 'Lumbricals (1,2)', catalogNames: ['Lumbricals (1,2)'],
    innervation: '正中神經，內側索／下幹，C8-T1。',
    insertion: '肌肉位於掌側屈肌腱旁且體積小；若需選擇性取樣，應以超音波辨認肌腹及掌側神經血管束。',
    activation: '請病人屈曲掌指關節並伸直指間關節。',
    clinicalPoints: ['可評估正中神經遠端運動支配，但通常 APB 更表淺且容易確認。', '僅在具特定鑑別需求時選用。'],
    anatomyPoints: ['掌側數位神經、血管與屈肌腱密集，盲刺風險與疼痛較高。', '建議超音波導引。'],
  },
  {
    id: 'supplement-palmar-interossei', chineseName: '掌側骨間肌', englishName: 'Palmar Interossei', catalogNames: ['Palmar Interossei'],
    innervation: '尺神經深支，內側索／下幹，C8-T1。',
    insertion: '掌側骨間肌位於掌骨間深層；先以手指內收確認功能，需取樣時以影像辨認目標掌骨間隙。',
    activation: '請病人將手指向中指方向內收。',
    clinicalPoints: ['可評估尺神經深支及 C8-T1，但 FDI／ADM 通常更易取樣。', '不宜只依共同的手指動作推定針尖位置。'],
    anatomyPoints: ['鄰近掌深弓與數位神經血管束。', '建議超音波導引，避免常規盲刺。'],
  },
  {
    id: 'supplement-adductor-pollicis', chineseName: '拇收肌', englishName: 'Adductor Pollicis', catalogNames: ['Adductor Pollicis'],
    innervation: '尺神經深支，內側索／下幹，C8-T1。',
    insertion: '在第一蹼間深層，以拇指抗阻內收確認；從背側或橈側接近時須先辨認 FDI 與目標肌層次。',
    activation: '請病人將拇指貼向食指並夾住紙張。',
    clinicalPoints: ['可評估尺神經深支與下幹／內側索病變。', '與 FDI 同區但功能與肌層不同，針位確認很重要。'],
    anatomyPoints: ['深部鄰近橈動脈及掌深弓。', '若無法可靠區分 FDI，採超音波導引。'],
  },
  {
    id: 'supplement-sartorius', chineseName: '縫匠肌', englishName: 'Sartorius', catalogNames: ['Sartorius'],
    innervation: '股神經前分支／直接肌支，L2-L3。',
    insertion: '由前上髂棘向內側膝部的走向，在近端大腿前內側以髖屈曲、外展及外旋觸診表淺帶狀肌腹。',
    activation: '請病人屈曲、外展並外旋髖關節，同時輕度屈膝。',
    clinicalPoints: ['可協助評估股神經較近端分支與 L2-L3 神經根。', '肌肉薄而斜走，應先完整觸診邊界。'],
    anatomyPoints: ['近端靠近腹股溝時，股神經血管束位於更內側。', '避免過度靠近前上髂棘，以減少接近外側股皮神經的機會。'],
  },
  {
    id: 'supplement-pectineus', chineseName: '恥骨肌', englishName: 'Pectineus', catalogNames: ['Pectineus'],
    innervation: '股神經為主，可有閉孔神經支配，L2-L3。',
    insertion: '位於股三角深層、腹股溝韌帶下方內側；以抗阻髖屈曲及內收確認，但表面觸診常不足。',
    activation: '請病人屈曲並內收髖關節。',
    clinicalPoints: ['可協助評估上腰神經根、股神經與閉孔神經的支配變異。', '因雙重支配變異，孤立異常不宜單獨定位。'],
    anatomyPoints: ['鄰近股動靜脈與股神經，建議超音波導引。', '無影像導引時應優先選擇較表淺替代肌。'],
  },
  {
    id: 'supplement-obturator-externus', chineseName: '閉孔外肌', englishName: 'Obturator Externus', catalogNames: ['Obturator Externus'],
    innervation: '閉孔神經後支，L3-L4。',
    insertion: '本工具目前沒有找到可驗證的一般 diagnostic needle EMG 路徑，因此不提供固定位置、角度或深度。',
    activation: '髖外旋與內收會同時募集多條深層髖肌，不能作為針位確認。',
    clinicalPoints: ['目前只找到深層髖部 anatomy／teaching 資料，未找到足以支持常規盲刺的肌肉專屬研究。', '通常先以較表淺的內收肌群回答定位問題。'],
    anatomyPoints: ['鄰近閉孔神經血管與內側旋股血管；若特殊情境確需取樣，須由具專門訓練者依院內程序決定影像策略。', '本頁不提供盲刺操作指示。'],
  },
  {
    id: 'supplement-gluteus-minimus', chineseName: '臀小肌', englishName: 'Gluteus Minimus', catalogNames: ['Gluteus Minimus'],
    innervation: '上臀神經，腰薦神經叢，L4-S1。',
    insertion: '位於臀中肌深層、髂骨外面與大轉子之間；表面 activation 無法可靠區分兩層。',
    activation: '請病人外展並內旋髖關節。',
    clinicalPoints: ['可評估上臀神經與 L5 為主的近端肌，但臀中肌或 TFL 通常較容易確認。', '需要區分臀中肌時應使用影像。'],
    anatomyPoints: ['上臀神經血管束位於臀肌層間。', '建議超音波導引，避免深度與層次誤判。'],
  },
  {
    id: 'supplement-piriformis', chineseName: '梨狀肌', englishName: 'Piriformis', catalogNames: ['Piriformis'],
    innervation: '梨狀肌神經，S1-S2。',
    insertion: '本工具目前沒有找到可驗證的一般 diagnostic needle EMG 路徑，因此不提供固定位置、角度或深度。',
    activation: '髖部外展／外旋會同時募集多條肌肉，不能作為針位確認。',
    clinicalPoints: ['外部圖譜明載深層短髖肌難以直接觀察，且缺乏足以支持一般診斷 EMG 的人類資料。', '若有特殊 deep-gluteal／sciatic localization 問題，結果仍須與較表淺的坐骨與非坐骨支配肌共同解讀。'],
    anatomyPoints: ['坐骨神經與臀部神經血管構造緊鄰；本頁不提供盲刺操作指示。', '是否使用影像須依個案、操作者專門訓練與院內程序決定。'],
  },
  {
    id: 'supplement-obturator-internus-gemelli', chineseName: '閉孔內肌／孖肌', englishName: 'Obturator Internus / Gemelli', catalogNames: ['Obturator Int / Gemelli'],
    innervation: '閉孔內肌與上孖肌通常由 nerve to obturator internus 支配；下孖肌通常由 nerve to quadratus femoris 支配，且可有變異。',
    insertion: '這是三條不同且可有支配變異的深層肌；本工具不把它們合併成一個固定 diagnostic needle route。',
    activation: '外旋髖關節會同時募集多條肌肉，不能證實個別肌肉的針位。',
    clinicalPoints: ['目前僅保留為 anatomy 分類提醒，不提供一般取樣 protocol。', '若需區分其中一肌，須先定義目標與臨床問題，再依專門訓練與院內程序處理。'],
    anatomyPoints: ['鄰近坐骨神經、陰部神經血管與骨盆構造；本頁不提供盲刺操作指示。', '上孖肌可見雙重支配等變異，不能以合併的 L5-S2 標籤作精準定位。'],
  },
  {
    id: 'supplement-quadratus-femoris', chineseName: '股方肌', englishName: 'Quadratus Femoris', catalogNames: ['Quadratus Femoris'],
    innervation: '股方肌神經，L4-S1。',
    insertion: '本工具目前沒有找到可驗證的一般 diagnostic needle EMG 路徑，因此不提供固定位置、角度或深度。',
    activation: '髖外旋與內收會同時募集多條深層肌，不能作為針位確認。',
    clinicalPoints: ['目前只找到 anatomy／teaching 資料，未找到足以支持常規 diagnostic needle sampling 的肌肉專屬研究。', '優先考慮能以較低風險回答相同問題的表淺肌。'],
    anatomyPoints: ['鄰近坐骨神經與內側旋股血管；本頁不提供盲刺操作指示。', '特殊情境是否使用影像，須依操作者專門訓練與院內程序決定。'],
  },
  {
    id: 'supplement-ehb', chineseName: '拇短伸肌', englishName: 'Extensor Hallucis Brevis', catalogNames: ['Extensor Hallucis Brevis'],
    innervation: '深腓神經，L5-S1。',
    insertion: 'SIU atlas 將 EDB 最內側肌束描述為 EHB；本頁不宣稱能用相同路徑完全隔離 EHB。',
    activation: '請病人伸展拇趾蹠趾關節，並觀察其他趾是否也同時伸展。',
    clinicalPoints: ['可提供 deep peroneal nerve／L5 的遠端資訊。', '肌腹很小且與 EDB 相連；若必須分離 EHB，需採能直接確認肌束的方法。'],
    anatomyPoints: ['足背動脈及深腓神經位於鄰近區域，進針前先觸診足背動脈。', '缺血、感染、嚴重水腫或皮膚脆弱時避免足背取樣。'],
  },
  {
    id: 'supplement-peroneus-brevis', chineseName: '腓骨短肌', englishName: 'Peroneus Brevis', catalogNames: ['Peroneus Brevis'],
    innervation: '淺腓神經，腓總神經，L5-S1。',
    insertion: '在小腿遠端外側、腓骨後方觸診肌腹；以抗阻足外翻確認，避開只剩肌腱的最遠端區域。',
    activation: '請病人外翻並輕度蹠屈足部。',
    clinicalPoints: ['可與腓骨長肌比較淺腓神經不同高度的支配。', '肌肉較遠端，對長度依賴性多發神經病變可能更敏感。'],
    anatomyPoints: ['淺腓神經在遠端轉為皮下，避免反覆橫向探針。', '確認針在肌腹而非腓骨肌腱。'],
  },
  {
    id: 'supplement-popliteus', chineseName: '膕肌', englishName: 'Popliteus', catalogNames: ['Popliteus'],
    innervation: '脛神經，L4-S1。',
    insertion: '本工具目前不提供常規 blind diagnostic needle route；外部 teaching atlas 指出此肌薄且鄰近膕血管。',
    activation: '屈膝時內旋脛骨是膕肌動作，但也不能單獨證實針位。',
    clinicalPoints: ['可提供脛神經近端分支資訊，但現有來源認為臨床效益有限。', 'Gastrocnemius、soleus 或 tibialis posterior 通常能以較低風險回答定位問題。'],
    anatomyPoints: ['膕動靜脈與脛神經位於鄰近深層；如特殊情境確需取樣，須依操作者專門訓練與院內程序決定影像策略。', '本頁不提供盲刺操作指示。'],
  },
  {
    id: 'supplement-fhl', chineseName: '拇長屈肌', englishName: 'Flexor Hallucis Longus', catalogNames: ['Flexor Hallucis Longus'],
    innervation: '脛神經；常列 L5-S1，部分參考資料延伸至 S2。',
    insertion: '位於小腿後方深層、偏腓側；以拇趾屈曲確認，但表淺屈肌可遮蔽目標。',
    activation: '請病人屈曲拇趾。',
    clinicalPoints: ['可評估脛神經、坐骨神經脛側分支與 L5-S2。', '深層肌盲刺準確度有限，單靠動作回饋不可排除誤入鄰肌。'],
    anatomyPoints: ['鄰近脛神經與後脛血管，建議超音波導引。', '抗凝或無法壓迫止血時優先選表淺替代肌。'],
  },
  {
    id: 'supplement-fdb', chineseName: '趾短屈肌', englishName: 'Flexor Digitorum Brevis', catalogNames: ['Flexor Digitorum Brevis'],
    innervation: '內側足底神經，S1-S2。',
    insertion: '位於足底中央表淺層；在足跟前方的肌腹區，以趾屈曲確認後進針。',
    activation: '請病人屈曲第二至第五趾。',
    clinicalPoints: ['可評估內側足底神經與遠端軸索病變，但足底取樣疼痛較明顯。', '僅在遠端資訊無法由較舒適肌肉取得時選用。'],
    anatomyPoints: ['避開內、外側足底神經血管走向與足底皮膚病灶。', '嚴重糖尿病足、缺血、感染或皮膚脆弱時避免取樣。'],
  },
  {
    id: 'supplement-foot-interossei', chineseName: '足部骨間肌', englishName: 'Interossei (Foot)', catalogNames: ['Interossei (Foot)'],
    innervation: '外側足底神經為主，S2-S3。',
    insertion: '位於蹠骨間隙；以趾外展或內收確認，但各肌體積小且難以表面觸診。',
    activation: '請病人外展或內收腳趾。',
    clinicalPoints: ['目前的外部定位來源只直接說明 first dorsal interosseous pedis，不能自動外推至全部足部骨間肌。', '可提供非常遠端的運動軸索資訊，但疼痛及非特異性異常限制常規使用。'],
    anatomyPoints: ['鄰近蹠背／蹠底動脈及神經分支，建議影像導引。', '缺血、感染、嚴重水腫或糖尿病足時避免取樣。'],
  },
  {
    id: 'supplement-eas', chineseName: '外肛門括約肌', englishName: 'External Anal Sphincter', catalogNames: ['Ext. Anal Sphincter'],
    innervation: '陰部神經下直腸支與直接薦神經分支，S2-S4。',
    insertion: '採側臥或截石位；在肛門緣外側的括約肌肌腹作表淺取樣。須先說明目的並取得明確同意。',
    activation: '請病人像忍住排便一樣收縮肛門。',
    clinicalPoints: ['用於特定圓錐、馬尾、陰部神經或括約肌功能評估。', '應由熟悉骨盆底 EDX 的醫師執行，並依院內規範安排隱私與陪同人員。'],
    anatomyPoints: ['避開肛門病灶、感染、近期手術區與顯著出血風險。', '不要朝直腸腔深刺；必要時採影像或專科定位。'],
  },
  {
    id: 'supplement-bulbocavernosus', chineseName: '球海綿體肌', englishName: 'Bulbocavernosus / Bulbospongiosus', catalogNames: ['Bulbocavernosus'],
    innervation: '陰部神經深支，S2-S4。',
    insertion: '屬會陰專科取樣；依性別與個別解剖，在可辨認的球海綿體肌肌腹表淺進針，須取得明確同意。',
    activation: '請病人收縮骨盆底，如中止排尿。',
    clinicalPoints: ['可用於特定薦髓、馬尾或陰部神經病變評估。', '應由熟悉骨盆底 EDX 的醫師執行，並遵循隱私、陪同與感染控制規範。'],
    anatomyPoints: ['鄰近尿道、陰部神經血管與生殖構造；不建議未受訓者盲刺。', '避開感染、近期手術與明顯出血風險區域。'],
  },
]
